set_property PACKAGE_PIN G11 [get_ports hvio_pllrefclk]
set_property IOSTANDARD LVCMOS33 [get_ports hvio_pllrefclk]
set_property PACKAGE_PIN L5 [get_ports io96_3a_pb1_fpga_rst_n]
set_property PACKAGE_PIN D3 [get_ports io96_3a_pb0]
set_property IOSTANDARD LVCMOS18 [get_ports io96_3a_pb0]
set_property PULLTYPE PULLUP [get_ports io96_3a_pb0]
set_property PULLTYPE PULLUP [get_ports io96_3a_pb1_fpga_rst_n]
set_property PACKAGE_PIN F13 [get_ports uart_rx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_pin]
set_property IOSTANDARD LVCMOS18 [get_ports io96_3a_pb1_fpga_rst_n]
set_property PACKAGE_PIN K12 [get_ports uart_tx_pin]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_pin]
set_property PACKAGE_PIN P11 [get_ports io96_3a_led0]
set_property IOSTANDARD LVCMOS33 [get_ports io96_3a_led0]

create_clock -period 10.000 -name hvio_pllrefclk -waveform {0.000 5.000} [get_ports hvio_pllrefclk]
